### ISSUE TITLE
Remove unnecessary warnings in danger

### ISSUE THREAD

**Issue by fabiorbap** [indigotech/danger#23]
- In the Onofre project, Danger is showing [warnings that are not meaningful or correct](https://www.evernote.com/l/AeFSYeGC2eJDW4gA1iB8NTeSkl0agDQB5IM), so it would be good if they could be removed so as not to pollute the PR

**Comment by eiditakahashi** [comment]
I was thinking in after getting all matches that has `http://...` check if contains `http:\/\/schemas.android.com\/apk\/res\/android` if it is the case, we skip the warning on this match.

What do you think? This url is used in another place besides these `.xml` files? @fabiorbap @melloflavio @felipesabino

**Comment by melloflavio** [comment]
@eiditakahashi 
I always prefer to limit the files being searched instead of changing the regex to a specific case.
If file path is `.*/(drawable|layout)/.*` do not apply this rule. I'm not sure if excluding `.*/res/.*` would work, we could be storing there config related data, or strings that refer to sites.

**Comment by fabiorbap** [comment]
@eiditakahashi The string `http:\/\/schemas.android.com\/apk\/res\/android` is used as a namespace in xml files, it only appears in them.

But I agree with @melloflavio , it would be better to ignore the paths instead of the url. It wouldn't be a good idea to ignore all the `res` folder, because you can put string constants in there too, so it would be useful if they were checked
